allowBuilds:
  '@google/genai': true
  '@parcel/watcher': true
  '@swc/core': true
  protobufjs: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - postcss@8.5.10
  - protobufjs@7.5.6
  - '@protobufjs/utf8@1.1.1'
  - ws@8.20.1
  - protobufjs@7.5.8
  - brace-expansion@5.0.6
onlyBuiltDependencies:
  - '@google/genai'
  - '@tailwindcss/oxide'
  - protobufjs
  - re2
  - sharp
  - unrs-resolver
overrides:
  '@protobufjs/utf8@<=1.1.0': ^1.1.1
  brace-expansion@>=5.0.0 <5.0.6: ^5.0.6
  js-yaml@<4.1.2: ^4.1.2
  postcss@<8.5.10: ^8.5.10
  protobufjs@<=7.5.5: ^7.5.6
  protobufjs@<=7.5.7: ^7.5.8
  vite@<8.0.16: ^8.0.16
  ws@>=8.0.0 <8.20.1: ^8.20.1
